@base_url = http://localhost:3000
@eventId = 001fcd07-92a5-4165-8da2-f483909e3c0c
@path = {{base_url}}/events/{{eventId}}/spots

### GET ALL SPOTS
# @name get_all_spots
GET {{path}}

### CREATE SPOT
# @name create_spot
POST {{path}}
Content-Type: application/json

{
  "name": "A1"
}

###
@spot_id = {{create_spot.response.body.id}}

### GET SPOT BY ID
# @name get_spot_by_id
GET {{path}}/{{spot_id}}

### UPDATE SPOT
# @name update_spot
PATCH {{path}}/{{spot_id}}
Content-Type: application/json

{
  "name": "A2"
}

### DELETE SPOT
# @name delete_spot
DELETE {{path}}/{{spot_id}}